# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm7435-modules/motorola/include
EXTRA_CFLAGS += -I$(srctree)/drivers/base

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/Module.symvers

sx931x_triple-y := sx9310_triple.o

obj-m += sx931x_triple.o
