# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm7435-modules/motorola/include \
		-I$(KERNEL_SRC)/../sm7435-modules/motorola/drivers/input/touchscreen/pt




obj-m += pt.o
pt-y := pt_core.o pt_mt_common.o
#pt-objs += pt_mta.o
pt-y += pt_mtb.o
pt-y += pt_btn.o
pt-y += pt_proximity.o
pt-y += pt_devtree.o pt_platform.o
pt-y += pt_i2c.o
#pt-objs += pt_spi.o
obj-m += cypsoc_picoleaf.o




