# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm7435-modules/motorola/include \

ifneq ($(filter m y,$(CONFIG_MMI_RELAY)),)
	EXTRA_CFLAGS += -DMMI_RELAY_MODULE
endif

focaltech_fps_mmi-y +=  ff_core.o ff_spi.o

obj-m += focaltech_fps_mmi.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_relay/$(GKI_OBJ_MODULE_DIR)/Module.symvers

