# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6450-modules/motorola/include \
		-I$(KERNEL_SRC)/../sm6450-modules/motorola/drivers/input/touchscreen/AW8680X


obj-m += AW8680X.o
AW8680X-y := aw8680x.o aw8680x_bin_parse.o aw_com_protocol.o aw_protocol_fun.o aw_protocol_map.o aw_soc_protocol_interface.o
