KERNEL_DIR_PATH = $(shell find $(TOP)/kernel/ -name "msm-*" | head -1 | grep -i "kernel/msm-*")

KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm7435-modules/motorola/include

EXTRA_CFLAGS += -I$(srctree)/drivers/base

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/Module.symvers

sx932x_sar-y := sx9325_sar.o

obj-m += sx932x_sar.o
